name: distributed-order-lab

services:
  order-db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: order_db
      POSTGRES_USER: order_user
      POSTGRES_PASSWORD: order_password
    volumes:
      - order-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U order_user -d order_db"]
      interval: 5s
      timeout: 3s
      retries: 10

  inventory-db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: inventory_db
      POSTGRES_USER: inventory_user
      POSTGRES_PASSWORD: inventory_password
    volumes:
      - inventory-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U inventory_user -d inventory_db"]
      interval: 5s
      timeout: 3s
      retries: 10

  product-db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: product_db
      POSTGRES_USER: product_user
      POSTGRES_PASSWORD: product_password
    volumes:
      - product-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U product_user -d product_db"]
      interval: 5s
      timeout: 3s
      retries: 10

  inventory-service:
    build:
      context: ./inventory-service
    environment:
      DB_URL: jdbc:postgresql://inventory-db:5432/inventory_db
      DB_USERNAME: inventory_user
      DB_PASSWORD: inventory_password
      SERVER_PORT: 8082
    ports:
      - "8082:8082"
    depends_on:
      inventory-db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:8082/actuator/health"]
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 20s

  product-service:
    build:
      context: ./product-service
    environment:
      DB_URL: jdbc:postgresql://product-db:5432/product_db
      DB_USERNAME: product_user
      DB_PASSWORD: product_password
      SERVER_PORT: 8083
    ports:
      - "8083:8083"
    depends_on:
      product-db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:8083/actuator/health"]
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 20s

  order-service:
    build:
      context: ./order-service
    environment:
      DB_URL: jdbc:postgresql://order-db:5432/order_db
      DB_USERNAME: order_user
      DB_PASSWORD: order_password
      SERVER_PORT: 8081
      INVENTORY_SERVICE_URL: http://inventory-service:8082
    ports:
      - "8081:8081"
    depends_on:
      order-db:
        condition: service_healthy
      inventory-service:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:8081/actuator/health"]
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 20s

volumes:
  order-db-data:
  inventory-db-data:
  product-db-data:
