spring:
  application:
    name: inventory-service
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/inventory_db}
    username: ${DB_USERNAME:inventory_user}
    password: ${DB_PASSWORD:inventory_password}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info

server:
  port: ${SERVER_PORT:8082}
